// scripts/pwa/vite-sw-plugin.ts
// Vite plugin that emits dist/app/sw.js - a small hand-written service
// worker, scoped to the app at /app/ (the site root is the landing page),
// that precaches the whole built app shell, so the app
// opens offline and installs as a PWA. Generated at build time rather than
// kept in public/ because the precache list has to name Vite's hashed
// output files, which only exist once the bundle is written - so the list is
// read from the written output directory, not from the in-memory bundle
// (that still holds the empty JS chunks of the CSS-only guide and changelog
// entries, which Vite drops before writing; precaching a file that 404s makes
// cache.addAll fail and the worker never installs). Build-only:
// main.ts never registers a service worker under `vite dev`, where cached
// modules would fight HMR.

import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import type { Plugin } from 'vite';

// Every file under dir, as /-separated paths relative to it. Dot-entries are
// skipped (dist/ can hold the public repo's .git checkout).
function listFiles(dir: string, prefix = ''): string[] {
  let files: string[] = [];
  for (const name of readdirSync(dir)) {
    if (name.startsWith('.')) continue;
    const full = path.join(dir, name);
    const rel = prefix ? `${prefix}/${name}` : name;
    if (statSync(full).isDirectory()) files = files.concat(listFiles(full, rel));
    else files.push(rel);
  }
  return files;
}

// Precache entries are site-root-relative paths (the build's assets and
// public files sit at the root, above the worker's /app/ scope), resolved
// against the site base.
function serviceWorkerSource(version: string, base: string, precache: string[]): string {
  return `// Generated by scripts/pwa/vite-sw-plugin.ts - do not edit.
const CACHE = 'lapline-${version}';
const BASE = ${JSON.stringify(base)};
const APP = BASE + 'app/';
const PRECACHE = ${JSON.stringify(precache)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll([APP, ...PRECACHE.map((f) => BASE + f)].map((f) => new URL(f, self.location.origin))))
      .then(() => self.skipWaiting())
  );
});

// Drops every older build's cache once this one takes over - including
// caches from before the rename, when they were prefixed 'pacebeat-'.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => (k.startsWith('lapline-') || k.startsWith('pacebeat-')) && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  // Same-origin GETs only - the opt-in geocoding/weather lookups (and
  // anything else cross-origin) always go straight to the network.
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;

  // Page loads: network first so a new deploy is picked up as soon as
  // it's reachable, falling back to the cached shell when offline.
  if (req.mode === 'navigate') {
    event.respondWith(
      fetch(req).catch(() => caches.match(new URL(APP, self.location.origin), { ignoreVary: true }))
    );
    return;
  }

  // Everything else is a content-hashed build asset or a static public
  // file: cache first, filling the cache on a miss. ignoreVary: the page's
  // crossorigin module/style requests carry an Origin header the precache
  // requests didn't, which a server's "Vary: Origin" would otherwise turn
  // into a cache miss - harmless to ignore when the URL is content-hashed.
  event.respondWith(
    caches.match(req, { ignoreVary: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) {
        const copy = res.clone();
        caches.open(CACHE).then((cache) => cache.put(req, copy));
      }
      return res;
    }))
  );
});
`;
}

// Builds before the landing page registered the worker at /sw.js with scope
// /. This stand-in replaces it for anyone who still has it: it unregisters
// itself (the /app/ worker above takes over the app), leaving caches to the
// new worker's own cleanup.
const RETIRED_ROOT_WORKER = `// Generated by scripts/pwa/vite-sw-plugin.ts - do not edit.
// Retired: the app's worker now lives at app/sw.js. This one removes itself.
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', (event) => {
  event.waitUntil(self.registration.unregister());
});
`;

export function serviceWorkerPlugin(): Plugin {
  let base = '/';
  return {
    name: 'lapline-service-worker',
    apply: 'build',
    configResolved(config) {
      base = config.base;
    },
    writeBundle(options) {
      const outDir = options.dir!;
      // Every written file except the HTML pages (the app page is cached
      // under its /app/ URL; the landing, guide and changelog pages aren't
      // part of the offline app), source maps and the workers themselves.
      // The landing page's own files (its tour video alone is ~2 MB) and the
      // guide/changelog chunks aren't part of the offline app either.
      const skip = (f: string) =>
        f.endsWith('.map') ||
        f.endsWith('.html') ||
        f === 'sw.js' ||
        f === 'app/sw.js' ||
        f.startsWith('landing/') ||
        /^assets\/(landing|guide-|changelog)/.test(f);
      const precache = listFiles(outDir).filter((f) => !skip(f)).sort();
      if (!precache.some((f) => /^assets\/app-.*\.js$/.test(f))) {
        throw new Error('service worker: no app entry chunk found in the build output');
      }
      // Hashing the bytes, not just the names: public/ files keep fixed
      // names, so the cache name then changes exactly when anything shipped
      // changes.
      const hash = createHash('sha256');
      for (const f of precache) hash.update(f).update(readFileSync(path.join(outDir, f)));
      const version = hash.digest('hex').slice(0, 12);
      mkdirSync(path.join(outDir, 'app'), { recursive: true });
      writeFileSync(path.join(outDir, 'app/sw.js'), serviceWorkerSource(version, base, precache));
      writeFileSync(path.join(outDir, 'sw.js'), RETIRED_ROOT_WORKER);
    }
  };
}
